language: python
python:
- '3.6'
#- '3.5' TODO: Compatibility with Py 3.5
#- '3.7' Does not exist in Travis CI yet

install:
- pip install -r requirements.txt
- pip install pytest
- pip install pprintpp
#- pip install -r requirements-dev.txt

script:
- 
- pytest tests/unit
#- pytest --cov . --cov-branch --cov-config=.coveragerc
