dist: xenial
language: python
python:
  - "3.7"
  - "3.6"
#- '3.5' TODO: Compatibility with Py 3.5

install:
- pip install -r requirements.txt
- pip install pytest
- pip install pprintpp
#- mkdir -p ~/.aws
#- echo "[default]\naws_access_key_id = $a\naws_secret_access_key = $s\n" > ~/.aws/credentials
#- cat ~/.aws/credentials
#- echo "$tester" > ~/.aws/test
#- pip install -r requirements-dev.txt

script:
- pytest tests
# - pytest tests/unit
#- pytest --cov . --cov-branch --cov-config=.coveragerc
